apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc }}
  postgres-username: {{ .Values.postgresql.username | b64enc }}