apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value:  {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: tasksdb
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-tasksdb-postgresql-secret
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-tasksdb-postgresql-secret
                  key: postgres-password